export const Users = [
    {
        id:1,
        profilePicture:"assets/person/1.jpeg",
        username:"Lional Messi",
    },
    {
        id:2,
        profilePicture:"assets/person/2.jpeg",
        username:"Cristiano Ronaldo",
    },
    {
        id:3,
        profilePicture:"assets/person/3.jpeg",
        username:"Gareth Bale",
    },
    {
        id:4,
        profilePicture:"assets/person/4.jpeg",
        username:"Mohommad Salah",
    },
    {
        id:5,
        profilePicture:"assets/person/5.jpeg",
        username:"Kylian Mbappe",
    },
    {
        id:6,
        profilePicture:"assets/person/6.jpeg",
        username:"Neymar JR",
    },
    {
        id:7,
        profilePicture:"assets/person/7.jpeg",
        username:"Ozil Mortez",
    },
    {
        id:8,
        profilePicture:"assets/person/8.jpeg",
        username:"Diago Maradona",
    },
    {
        id:9,
        profilePicture:"assets/person/9.jpeg",
        username:"Barce Mel",
    },
    {
        id:10,
        profilePicture:"assets/person/10.jpeg",
        username:"Lianado Dicaprio",
    },

];

export const Posts = [
    {
        id:1,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/1.jpeg",
        date:"5 mins ago",
        userId:1,
        like:32,
        comment:9,
    },
    {
        id:2,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/2.jpeg",
        date:"20 mins ago",
        userId:2,
        like:20,
        comment:19,
    },
    {
        id:3,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/3.jpeg",
        date:"15 mins ago",
        userId:3,
        like:56,
        comment:29,
    },
    {
        id:4,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/4.jpeg",
        date:"12 mins ago",
        userId:4,
        like:89,
        comment:15,
    },
    {
        id:5,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/5.jpeg",
        date:"49 mins ago",
        userId:5,
        like:45,
        comment:10,
    },
    {
        id:6,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/6.jpeg",
        date:"36 mins ago",
        userId:6,
        like:92,
        comment:8,
    },
    {
        id:7,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/7.jpeg",
        date:"55 mins ago",
        userId:7,
        like:54,
        comment:19,
    },
    {
        id:8,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/8.jpeg",
        date:"58 mins ago",
        userId:8,
        like:63,
        comment:16,
    },
    {
        id:9,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/9.jpeg",
        date:"22 mins ago",
        userId:9,
        like:42,
        comment:18,
    },
    {
        id:10,
        desc:"Love For All, Hatred For None.",
        photo:"assets/post/10.jpeg",
        date:"1 mins ago",
        userId:10,
        like:48,
        comment:26,
    },
];